/*
 * This source file was generated by the Gradle 'init' task
 */
package consumer;

public class Consumer {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Consumer().getGreeting());
    }
}
